# Generated by Django 3.2.12 on 2022-11-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('description', models.CharField(default='None', max_length=100)),
                ('address', models.CharField(default='None', max_length=100)),
                ('service', models.CharField(max_length=100)),
            ],
        ),
    ]
